name: Training
run-name: ${{ github.actor }} is training a new model ğŸš€
on: [push]

jobs:
  train:
    runs-on: self-hosted
    container:
      image: raffivk/dataset-server:latest  # TODO: Move to TC space
    
    steps:
      - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "ğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."

      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: List files in the repository
        run: ls /__w/SMOKE/SMOKE

    #   - name: Run training script
    #     run: python evaluate.py
